# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Core Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Only allow one build per branch at a time except on main.
# This takes advantage of the lazy evaluation of the "||" operator. When the ref is main
# the run_number will be included in the concurrency group making it unique but when
# the ref is not main it will evaluate to false and the second half of the operator is
# never evaluated, so the group is the same for all runs on that pr/branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .'[dev]'
    - name: Run Ruff Linter
      run: ruff check . --output-format=github
    - name: Run Ruff Formatter
      run: ruff format . --diff
    - name: Run mypy
      run: |
        mypy .
    - name: Test with pytest
      run: |
        pytest
